host:
  node-1: node-1
  node-10: node-10
  node-11: node-11
  node-12: node-12
  node-13: node-13
  node-14: node-14
  node-15: node-15
  node-16: node-16
  node-17: node-17
  node-18: node-18
  node-19: node-19
  node-2: node-2
  node-20: node-20
  node-3: node-3
  node-4: node-4
  node-5: node-5
  node-6: node-6
  node-7: node-7
  node-8: node-8
  node-9: node-9
